[project]
protostar-version = "0.9.0"
lib-path = "lib"

[contracts]
gateway = ["src/dex/gateway.cairo"]
storage = ["src/dex/storage.cairo"]
l2EthRemoteCore = ["src/crosschain/l2_eth_remote_core.cairo"]
l2EthRemoteEIP712 = ["src/crosschain/l2_eth_remote_eip_712.cairo"]
ERC20 = ["src/ERC20/ERC20.cairo"]

[profile.testnet.project]
gateway-url = "http://127.0.0.1:5050/"
chain-id = 1536727068981429685321