["protostar.config"]
protostar_version = "0.4.1"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
gateway = [
    "src/dex/gateway.cairo",
]
l2EthRemoteCore = [
    "src/crosschain/l2_eth_remote_core.cairo",
]
l2EthRemoteEIP712 = [
    "src/crosschain/l2_eth_remote_eip_712.cairo",
]
ERC20 = [
    "src/ERC20/ERC20.cairo",
]