["protostar.config"]
protostar_version = "0.4.1"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
gateway = [
    "src/dex/gateway.cairo",
    # "src/dex/markets.cairo",
    # "src/dex/balances.cairo",
    # "src/dex/limits.cairo",
    # "src/dex/orders.cairo",
    # "src/dex/structs.cairo",
    # "src/dex/events.cairo",
]
l2EthRemoteCore = [
    "src/crosschain/l2_eth_remote_core.cairo",
]
l2EthRemoteEIP712 = [
    "src/crosschain/l2_eth_remote_eip_712.cairo",
]

["profile.testnet.protostar.deploy"]
network="testnet"
gateway-url="https://alpha4-2.starknet.io/"
chain-id=1536727068981429685321