["protostar.config"]
protostar_version = "0.4.1"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
orders = [
    "src/tree/orders.cairo",
]
limits = [
    "src/tree/limits.cairo",
]
balances = [
    "src/tree/balances.cairo",
]
markets = [
    "src/tree/markets.cairo",
]